apiVersion: v1
kind: ConfigMap
metadata:
  name: config-loja
data:
  DB_HOST: "postgres-service"
  DB_NAME: "pedidos_db"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-service:4318/v1/traces"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-loja
type: Opaque
stringData:
  DB_USER: "user_veloz"
  DB_PASS: "pass_veloz"